name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]  # Name of our CI workflow
    types:
      - completed # Only run if the CI pipeline has completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if the CI pipeline has passed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@6d4b68b490aef8836e8fb5e50ee7b3bdfa5894f0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker backend
        id: push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./backend/Dockerfile
          push: true
          tags: el7s1a/simple-monitoring

      - name: Build and push Docker frontend
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./frontend/Dockerfile
          push: true
          tags: el7s1a/simple-monitoring








