name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]  # Name of our CI workflow
    types:
      - completed # Only run if the CI pipeline has completed

jobs:
  build:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if the CI pipeline has passed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@6d4b68b490aef8836e8fb5e50ee7b3bdfa5894f0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: el7s1a/simple-monitoring


      - name: Build and push Docker backend
        id: push
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1
        with:
          context: .
          file: ./LogMeIn/simple-monitoring/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      
   
          
      - name: Build and push Docker frontend
        uses: docker/build-push-action@v4
        with:
          context: ./LogMeIn/simple-monitoring/frontend/
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/el7s1a/simple-monitoring
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true




















